version: '3.8'

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  database:
